# This is a basic workflow that is manually triggered

name: Publish Docs to Readme.io

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: readmeio/rdme@7.0.3
      with:
        rdme: docs ./ --key=PeA1AWLWoctIJLRwI5EW3wg1GXhHEJxI --version=1.0